### ISSUE TITLE
Running screen.sh on Linux

### ISSUE THREAD

**Issue by LeoDoesThings** [DougTy/concord#117]
I am getting this error when trying to run `screen.sh`

$ node ./screen.sh
/app/screen.sh:2
screen -L -A -m -d -S concord node index.js
                                       ^^^^^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

I have no idea what this means

**Comment by DougTy** [comment]
`screen.sh` isn't a node script. Run that same command without "node".

Just a reminder that this isn't a support forum. Thanks.
